# Generated by Django 5.2.7 on 2025-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0003_alter_member_color_alter_member_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/images', verbose_name='Image'),
        ),
    ]
