# Generated by Django 5.2.7 on 2025-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members_app", "0004_alter_member_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Path to image in S3 storage",
                max_length=500,
                null=True,
                verbose_name="Image",
            ),
        ),
    ]
