# Generated by Django 5.2.7 on 2025-11-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
